# -*- coding: utf-8 -*-
"""ejercicioss

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Fp2rEyVw1WbZarD7hLZzp55LnOncefs
"""

# Abro el archivo en modo Write Extended.
# Si el archivo no existe, lo genera. Si existe, lo remplaza.
# Los contenidos van en secuencia.
archivo="colores.txt"
f = open(archivo,"w+")
# Escribo 4 contenidos en secuencia.
f.write("Blanco")
f.write("Negro")
f.write("Naranja")
# Cierro el archivo.
f.close()

# Para saltos de línea, se utiliza \n
# Abro el archivo en modo Write Extended
archivo="colores.txt"
f = open(archivo,"w+")
# Escribo 4 líneas adicionales.
f.write("Rojo\n")
f.write("Amarillo\n")
f.write("Verde\n")
# Agregando los elementos de un iterable
mas_colores=["Morado\n","Celeste\n","Rosa\n"]
f.writelines(mas_colores)
# Cierro el archivo.
f.close()

archivo="colores.txt"
f = open(archivo,"a+")
# Agregando los elementos de un iterable
mas_colores=["Morado\n","Celeste\n","Rosa\n"]
f.writelines(mas_colores)
# Cierro el archivo.
f.close()

# Abro el archivo en modo lectura
archivo="colores.txt"
f = open(archivo,"r")
# Leo únicamente los primeros 5 caracteres del archivo.
contenido=f.read(5)
# Muestro el contenido
print(contenido)
# Leo otros 5 caracteres del archivo.
contenido=f.read(5)
# Muestro el contenido
print(contenido)
# Cierro el archivo.
f.close()

# Abro el archivo en modo lectura
archivo="colores.txt"
f = open(archivo,"r")
# Leo únicamente la primer línea del archivo.
contenido=f.readline()
# Muestro el contenido
print(contenido)
# Leo siguiente línea
contenido=f.readline()
# Muestro el contenido
print(contenido)
# Cierro el archivo.
f.close()

# Abro el archivo en modo lectura
archivo="colores.txt"
f = open(archivo,"r")
# Leo únicamente los primeros 5 caracteres del arvhivo.
for linea in f:
 print(">", linea)
# Cierro el archivo.
f.close()
print(f.closed)

# Lista a escribir en un archivo.
marcas=["Audi\n","Alfa Romeo\n","BMW\n","Mercedes Benz\n"]
# Se abre en modo Write Extended, que permite lectura.
with open("marcas.txt","w+") as f:
 # Escribe cada elemento de la lista como una línea
 f.writelines(marcas)
 # Se va al inicio del archivo.
 f.seek(0,0)
 # Lee secuencialmente el archivo, desde el inicio.
 for linea in f:
  print(linea)

# Datos iniciales. Entradas es una lista que contiene listas.
Entradas=[
 ['correo','nombre','telefono'],
 ['juan@gmail.com','Juan','8123232323'],
 ['maria@gmail.com','Maria','5545454545'],
 ['diana@homail.com','Diana','4490909090']
]
for e in Entradas:
 print(f'{e[0]}|{e[1]}|{e[2]}')

# Se importa el módulo para trabajar con JSON.
import json
# Se crea un objeto de muestra, para serializar.
Original=[
 ['correo','nombre','telefono'],
 ['juan@gmail.com','Juan','8123232323'],
 ['maria@gmail.com','Maria','5545454545'],
 ['diana@homail.com','Diana','4490909090']
]
print(">> Tipo del objeto.\n")
print(type(Original))
print("\n>> Contenido del objeto.\n")
print(Original)
print("\n>> Serialización a JSON.\n")
Original_JSON=json.dumps(Original,indent=4)
print(Original_JSON)
print("\n>> Deserialización desde JSON.\n")
Nueva_Lista=json.loads(Original_JSON)
print(Nueva_Lista)
print(type(Nueva_Lista))
print("\n>> Comprobando igualdad de objetos.\n")
print(Original==Nueva_Lista)